### ISSUE TITLE
ChefSpec Custom Matchers

### ISSUE THREAD

**Issue by aaroncline** [nathwill/chef-nomad#38]
Hi Nathan:

Is it just me or are the custom matchers for the new custom resources not present or functional?  

We had some chefspec tests in a wrapper cookbook that is now broken and I can't find a way to get them working again.  Just curious if this was intentional and if they will be back eventually?

Thanks for a great and constantly updating cookbook.

Aaron

**Comment by nathwill** [comment]
@aaroncline are you using chefspec < 7.1.0 by chance? i removed them because chefspec is supposed to [autogenerate](https://github.com/chefspec/chefspec#automatic-matchers) them now (though i don't think we actually test for matcher existence in this cookbook, either, so probably worth at least doing that).

**Comment by aaroncline** [comment]
@nathwill    Oh yeah.  Our chefdk is pinned way back.  We haven't yet made the jump to chef-client 13, let alone 14.  For now we removed the tests we were doing and upgraded the cookbook and nomad anyway.  Everything worked really well.  Looks like we have yet another reason to do our upgrading.

Thanks for the information.
