### ISSUE TITLE
Bad type of config property for nomad_plugin_config 

### ISSUE THREAD

**Issue by Denkaspb** [nathwill/chef-nomad#53]
Hello!
function nomad_plugin_config not work correctly, because for config property defined bad data type: Array
nomad agent can`t start, after deploy plugin configuration with array type, nomad expecting string type there.

`nomad[13910]: ==> Error loading configuration from /etc/nomad.conf.d: Error loading /etc/nomad.conf.d/docker.plugin.json: expected: STRING got: LBRACK`

code from recipe:

> plugin_conf = {
>   volumes: {
>     enabled: true
>   },
>   logging: {
>     type: 'journald'
>   },
>   auth: {
>     config: '/etc/docker/docker-auth.json'
>   }
> }.to_a
> 
> nomad_plugin_config 'docker' do
>   args []
>   config plugin_conf
> end

https://github.com/nathwill/chef-nomad/blob/13b07643022fe87b0ca60d87fc8d1ae56e5982cd/libraries/data.rb#L197

**Comment by dbresson** [comment]
I believe your problem is that you're just passing it a broken structure. The problem is that we're generating json configs instead of hcl configs, and the json configs aren't documented or very easy to understand.

The config block in hcl is technically repeatable, so the json expects an array of objects, one for each time you specify "config". To get that result, we accept an array of ruby hashes.

This is how I'm using this resource in the cookbook I maintain that uses it:

```
nomad_plugin_config 'docker' do
  config([{
    'auth': [{
      'config': '/root/.docker/config.json'
    }],
  }])
end
```

It would be nice to better validate the structure, or even better, switch to hcl so we can accept something that is more intuitive.

**Comment by Denkaspb** [comment]
> I believe your problem is that you're just passing it a broken structure. The problem is that we're generating json configs instead of hcl configs, and the json configs aren't documented or very easy to understand.
> 
> The config block in hcl is technically repeatable, so the json expects an array of objects, one for each time you specify "config". To get that result, we accept an array of ruby hashes.
> 
> This is how I'm using this resource in the cookbook I maintain that uses it:
> 
> ```
> nomad_plugin_config 'docker' do
>   config([{
>     'auth': [{
>       'config': '/root/.docker/config.json'
>     }],
>   }])
> end
> ```
> 
> It would be nice to better validate the structure, or even better, switch to hcl so we can accept something that is more intuitive.

Great, i`m understand and try this solution! Thanks a lot for answer!
